services:
    kernel.listener.subdomain_listener:
        class: LunaAtra\CoreBundle\Listener\SubdomainListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onDomainParse }
    privacy.twig.core_extension:
        class: LunaAtra\CoreBundle\Twig\CoreExtension
        tags:
            - { name: twig.extension }