<?php

namespace LunaAtra\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
   public function findLastSameActivity($activity)
    {
        $dateTime = new \DateTime("now");
        $dateTime->modify("-30 minutes");

        $query = $this->createQueryBuilder("a")
        ->where("a.seeder = :seeder")
        ->andWhere("a.translation = :translation")
        ->andWhere("a.data = :data")
        ->andWhere("a.date > :date")
        ->setParameter("seeder", $activity->getSeeder() )
        ->setParameter("translation", $activity->getTranslation() )
        ->setParameter("data",serialize($activity->getData() ) )
        ->setParameter("date", $dateTime  )
        ->getQuery();
        return $query->getResult();

    }
}
