<?php

namespace LunaAtra\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
   public function findLastSameActivity($activity)
    {
        $dateTime = new \DateTime("now");
        $dateTime->modify("-30 minutes");
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM CoreBundle:Activity a 
                            WHERE a.seeder = :seeder 
                            AND a.translation = :translation
                            AND a.data = :data
                            AND a.date > :date')
            ->setParameters(array(
                'seeder' => $activity->getSeeder() ,
                'translation' => $activity->getTranslation()   ,
                'data' => serialize($activity->getData() )   ,
                'date' => $dateTime 
            ))
            ->getResult();
    }
}
