<?php

namespace LunaAtra\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharactRepository extends EntityRepository
{
}
