<?php

namespace LunaAtra\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FriendsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendsRepository extends EntityRepository
{
    public function getFriendStatus($connectedUser, $profile)
    {
        if($connectedUser == $profile) return false;
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM ProfileBundle:Friends a 
                            WHERE ( a.requested = :friend1
                            AND a.requester = :friend2 )
                            OR ( a.requested = :friend2
                            AND a.requester = :friend1 )
                            ')
            ->setParameters(array(
                'friend1' => $connectedUser, 
                'friend2' => $profile 
            ))
            ->getOneOrNullResult();

    }

    public function getFriendList($user)
    {
        $friends1 = $this->getEntityManager()
            ->createQuery('SELECT a.requested FROM ProfileBundle:Friends a 
                            WHERE ( a.requester = :user )
                            ')
            ->setParameters(array(
                'user' => $user
            ))
            ->getResult();

       $friends2 = $this->getEntityManager()
            ->createQuery('SELECT a.requester FROM ProfileBundle:Friends a 
                            WHERE ( a.requested = :user )
                            ')
            ->setParameters(array(
                'user' => $user
            ))
            ->getResult();
        return array_merge($friends1, $friend2);
    }

}
